name: Django CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change this to your default branch if it's different.
  pull_request:
    branches:
      - master  # Ensure this runs for pull requests to the main branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use the Python version your project requires.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test

      - name: Deploy to production (optional)
        if: success()
        run: |
          # Add deployment commands if needed, such as:
          # ./deploy.sh or other commands to deploy to your server or cloud provider.
